### ISSUE TITLE
ImportError: DLL load failed while importing _gdal

### ISSUE THREAD

**Issue by pomeloyou** [Narayana-Rao/polsartools#1]
When I run the test_functions.py, there is a ImportError. I have installed all prerequesites, but it still didn`t work. Here is the traceback below:
```
Traceback (most recent call last):
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\osgeo\__init__.py", line 29, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\Miniconda3\envs\pytorch\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "f:/ViT-CNN/ReadData.py", line 3, in <module>
    from osgeo import gdal
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\osgeo\__init__.py", line 45, in <module>
    _gdal = swig_import_helper()
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\osgeo\__init__.py", line 41, in swig_import_helper
    raise ImportError(traceback_string + '\n' + msg)
ImportError: Traceback (most recent call last):
  File "D:\Miniconda3\envs\pytorch\lib\site-packages\osgeo\__init__.py", line 29, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\Miniconda3\envs\pytorch\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: 找不到指定的模块。

On Windows, with Python >= 3.8, DLLs are no longer imported from the PATH.
If gdalXXX.dll is in the PATH, then set the USE_PATH_FOR_GDAL_PYTHON=YES environment variable
to feed the PATH into os.add_dll_directory().
```
I've been looking for a solution to this but can't seem to figure out how to fix this.

**Comment by Narayana-Rao** [comment]
Thank you, @pomeloyou, for reporting the issue. This issue is because of ```gdal``` version, downgrading ```gdal``` should fix this. Please try the following. 
```conda install gdal=3.0```

**Comment by pomeloyou** [comment]
Thank you, I will try for this.

**Comment by pomeloyou** [comment]
It worked. Thank you very much.
